version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /mnt/nvme/homeassistant/config:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /mnt/nvme/mosquitto/config:/mosquitto/config
      - /mnt/nvme/mosquitto/data:/mosquitto/data
      - /mnt/nvme/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  v4l2rtspserver:
    container_name: v4l2rtspserver
    image: mpromonet/v4l2rtspserver
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
    command: "-F 25 -H 720 -W 1280"
    ports:
      - 8554:8554
    