
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: zoneminder

zoneminder:
  - host: localhost
    ssl: false
    verify_ssl: false

# Example configuration.yaml entry
camera:
  - platform: zoneminder