version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /mnt/nvme/homeassistant/config:/config
      - /mnt/nvme/ssl:/ssl
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /mnt/nvme/mosquitto/config:/mosquitto/config
      - /mnt/nvme/mosquitto/data:/mosquitto/data
      - /mnt/nvme/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=<your duck domain subdomain>
      - TOKEN=<your duckdns token>
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - /mnt/nvme/duckdns/config:/config #optional
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=<yourducksubdomain>.duckdns.org
      - VALIDATION=http
      - SUBDOMAINS=www, #optional
      #- CERTPROVIDER= #optional
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      - EMAIL= <your email>
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      #- STAGING=false #optional
    volumes:
      - /mnt/nvme/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  v4l2rtspserver:
    container_name: v4l2rtspserver
    image: mpromonet/v4l2rtspserver
    restart: unless-stopped
    devices:
      - /dev/video1:/dev/video1
    command: "-F 25 -H 720 -W 1280"
    ports:
      - 8554:8554
    